In [1]:
import pandas as pd
import sqlite3
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
cust_conn = sqlite3.connect("Customer Support & Call Center Performance")
cust_cursor = cust_conn.cursor()

In [3]:
cust_cursor.execute('''
CREATE TABLE IF NOT EXISTS call_logs (
Cust_id INTEGER,
Call_Time REAL,
Agent_Name TEXT
)
''')

In [4]:
cust_cursor.execute('DROP TABLE IF EXISTS call_logs')

In [5]:
cust_cursor.execute('''
CREATE TABLE IF NOT EXISTS call_logs (
    Call_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Cust_Id INTEGER,
    Agent_Name TEXT,
    Call_Duration_Minutes REAL,
    Call_Topic TEXT,
    First_Call_Resolution TEXT,
    CSAT_Rating INTEGER,
    Call_Status TEXT
)
''')

In [6]:
cust_conn.commit()

In [7]:
call_data = [
    (101, 'Anjali', 5.5, 'Billing Issue', 'Yes', 5, 'Resolved'),
    (102, 'Rohan', 12.2, 'Move-In Request', 'No', 3, 'Resolved'),
    (103, 'Anjali', 8.0, 'Technical Support', 'Yes', 4, 'Resolved'),
    (104, 'Rahul', 3.1, 'Billing Issue', 'Yes', 5, 'Resolved'),
    (105, 'Rohan', 15.4, 'Move-Out Request', 'No', 2, 'Pending'),
    (106, 'Anjali', 2.5, 'General Inquiry', 'Yes', 4, 'Resolved'),
    (107, 'Rahul', 18.1, 'Move-In Request', 'No', 1, 'Resolved'),
    (108, 'Rohan', 6.2, 'Billing Issue', 'Yes', 5, 'Resolved'),
    (109, 'Anjali', 14.0, 'Technical Support', 'No', 3, 'Pending'),
    (110, 'Rahul', 4.8, 'General Inquiry', 'Yes', 4, 'Resolved')
]

In [8]:
cust_cursor.executemany(''' INSERT INTO call_logs (Cust_Id, Agent_Name, Call_Duration_Minutes, Call_Topic, First_Call_Resolution, CSAT_Rating, Call_Status)
VALUES (?, ?, ?, ?, ?, ?, ?)''', call_data)

In [9]:
cust_conn.commit()

In [10]:
df = "SELECT * FROM call_logs"

In [11]:
result = pd.read_sql(df,cust_conn)
result

,Call_ID,Cust_Id,Agent_Name,Call_Duration_Minutes,Call_Topic,First_Call_Resolution,CSAT_Rating,Call_Status
0,1,101,Anjali,5.5,Billing Issue,Yes,5,Resolved
1,2,102,Rohan,12.2,Move-In Request,No,3,Resolved
2,3,103,Anjali,8.0,Technical Support,Yes,4,Resolved
3,4,104,Rahul,3.1,Billing Issue,Yes,5,Resolved
4,5,105,Rohan,15.4,Move-Out Request,No,2,Pending
5,6,106,Anjali,2.5,General Inquiry,Yes,4,Resolved
6,7,107,Rahul,18.1,Move-In Request,No,1,Resolved
7,8,108,Rohan,6.2,Billing Issue,Yes,5,Resolved
8,9,109,Anjali,14.0,Technical Support,No,3,Pending
9,10,110,Rahul,4.8,General Inquiry,Yes,4,Resolved

In [12]:
avg_query = "SELECT AVG(Call_Duration_Minutes) AS 'Average_time' FROM call_logs"

In [13]:
result1 = pd.read_sql(avg_query,cust_conn)
result1

   Average_time
0          8.98

In [14]:
#Task2: Write an SQL query to retrieve all columns from the call_logs table where the CSAT_Rating is strictly greater than 3.

In [15]:
CSAT_Rating = "SELECT * FROM call_logs WHERE CSAT_Rating > 3"

In [16]:
result2 = pd.read_sql(CSAT_Rating,cust_conn)
result2

,Call_ID,Cust_Id,Agent_Name,Call_Duration_Minutes,Call_Topic,First_Call_Resolution,CSAT_Rating,Call_Status
0,1,101,Anjali,5.5,Billing Issue,Yes,5,Resolved
1,3,103,Anjali,8.0,Technical Support,Yes,4,Resolved
2,4,104,Rahul,3.1,Billing Issue,Yes,5,Resolved
3,6,106,Anjali,2.5,General Inquiry,Yes,4,Resolved
4,8,108,Rohan,6.2,Billing Issue,Yes,5,Resolved
5,10,110,Rahul,4.8,General Inquiry,Yes,4,Resolved

In [17]:
#Task 3: Write an SQL query to retrieve all columns from the call_logs table where the Call_Status is exactly equal to 'Pending'.

In [18]:
Pending_Status = "SELECT * FROM call_logs WHERE Call_Status = 'Pending'"

In [19]:
result3 = pd.read_sql(Pending_Status,cust_conn)
result3

,Call_ID,Cust_Id,Agent_Name,Call_Duration_Minutes,Call_Topic,First_Call_Resolution,CSAT_Rating,Call_Status
0,5,105,Rohan,15.4,Move-Out Request,No,2,Pending
1,9,109,Anjali,14.0,Technical Support,No,3,Pending

In [20]:
#Task 4: Write an SQL query to retrieve all columns from the call_logs table where the Agent_Name is 'Anjali' AND the Call_Duration_Minutes is greater than 5.

In [21]:
query = "SELECT * FROM call_logs WHERE Agent_Name = 'Anjali' AND Call_Duration_Minutes > 5 "

In [22]:
result4 = pd.read_sql(query,cust_conn)
result4

,Call_ID,Cust_Id,Agent_Name,Call_Duration_Minutes,Call_Topic,First_Call_Resolution,CSAT_Rating,Call_Status
0,1,101,Anjali,5.5,Billing Issue,Yes,5,Resolved
1,3,103,Anjali,8.0,Technical Support,Yes,4,Resolved
2,9,109,Anjali,14.0,Technical Support,No,3,Pending

In [23]:
#Task 5: Write an SQL query to retrieve all columns from the call_logs table and sort the results by Call_Duration_Minutes in descending order (from highest to lowest).

In [24]:
query1 = "SELECT * FROM call_logs ORDER BY Call_Duration_Minutes DESC"

In [25]:
result5 = pd.read_sql(query1,cust_conn)
result5

,Call_ID,Cust_Id,Agent_Name,Call_Duration_Minutes,Call_Topic,First_Call_Resolution,CSAT_Rating,Call_Status
0,7,107,Rahul,18.1,Move-In Request,No,1,Resolved
1,5,105,Rohan,15.4,Move-Out Request,No,2,Pending
2,9,109,Anjali,14.0,Technical Support,No,3,Pending
3,2,102,Rohan,12.2,Move-In Request,No,3,Resolved
4,3,103,Anjali,8.0,Technical Support,Yes,4,Resolved
5,8,108,Rohan,6.2,Billing Issue,Yes,5,Resolved
6,1,101,Anjali,5.5,Billing Issue,Yes,5,Resolved
7,10,110,Rahul,4.8,General Inquiry,Yes,4,Resolved
8,4,104,Rahul,3.1,Billing Issue,Yes,5,Resolved
9,6,106,Anjali,2.5,General Inquiry,Yes,4,Resolved

In [26]:
#Task 6: Write an SQL query to find the total number of calls received for each Call_Topic. Your output should show the Call_Topic and the count of calls as Total_Calls, grouped by the topic.

In [27]:
query2 = "SELECT Call_Topic, COUNT(Call_Topic) AS 'Total_Call' FROM call_logs GROUP BY Call_Topic"

In [28]:
result6 = pd.read_sql(query2,cust_conn)
result6

          Call_Topic  Total_Call
0      Billing Issue           3
1    General Inquiry           2
2    Move-In Request           2
3   Move-Out Request           1
4  Technical Support           2

In [29]:
#Task 7: Write an SQL query to calculate the average call duration for each Call_Topic. Your output should display the Call_Topic and the average duration as Avg_Duration, grouped by the topic.

In [30]:
query3 = "SELECT Call_Topic, AVG(Call_Duration_Minutes) AS 'Avg_Duration' FROM call_logs GROUP BY Call_Topic"

In [31]:
result7 = pd.read_sql(query3,cust_conn)
result7

          Call_Topic  Avg_Duration
0      Billing Issue      4.933333
1    General Inquiry      3.650000
2    Move-In Request     15.150000
3   Move-Out Request     15.400000
4  Technical Support     11.000000

In [32]:
#Task 8: Write an SQL query to find the maximum call duration and the minimum call duration from the entire call_logs table. Label the columns as Max_Duration and Min_Duration.

In [33]:
query4 = "SELECT MAX(Call_Duration_Minutes) AS 'Max_Duration', MIN(Call_Duration_Minutes) AS 'Min_Duration' FROM call_logs"

In [34]:
result8 = pd.read_sql(query4,cust_conn)
result8

   Max_Duration  Min_Duration
0          18.1           2.5

In [35]:
#Task 9: Write an SQL query to calculate the Total Number of Calls and the Average CSAT Rating for each Agent_Name. Your output should show Agent_Name, Total_Calls, and Avg_CSAT, grouped by the agent's name.

In [36]:
query5 = "SELECT Agent_Name, COUNT(Call_Duration_Minutes) AS 'Total_Calls', AVG(CSAT_Rating) AS 'Avg_CSAT' FROM call_logs GROUP BY Agent_Name"

In [37]:
result9 = pd.read_sql(query5,cust_conn)
result9

  Agent_Name  Total_Calls  Avg_CSAT
0     Anjali            4  4.000000
1      Rahul            3  3.333333
2      Rohan            3  3.333333

In [38]:
#Task 10: Write an SQL query to retrieve all columns from the call_logs table where the First_Call_Resolution is 'No' AND the Call_Status is 'Pending'.

In [39]:
query6 = "SELECT * FROM call_logs WHERE First_Call_Resolution = 'No' AND Call_Status = 'Pending'"

In [40]:
result10 = pd.read_sql(query6,cust_conn)
result10

,Call_ID,Cust_Id,Agent_Name,Call_Duration_Minutes,Call_Topic,First_Call_Resolution,CSAT_Rating,Call_Status
0,5,105,Rohan,15.4,Move-Out Request,No,2,Pending
1,9,109,Anjali,14.0,Technical Support,No,3,Pending

In [41]:
#Task 11: Write an SQL query to retrieve Call_ID, Agent_Name, CSAT_Rating, and a new custom column called Satisfaction_Status.

In [42]:
query11 = "SELECT Call_ID, Agent_Name, CSAT_Rating, CASE WHEN CSAT_Rating >= 4 THEN 'Satisfied' ELSE 'Dissatisfied' END AS 'Satisfaction_Status' FROM call_logs "

In [43]:
result11 = pd.read_sql(query11,cust_conn)
result11

   Call_ID Agent_Name  CSAT_Rating Satisfaction_Status
0        1     Anjali            5           Satisfied
1        2      Rohan            3        Dissatisfied
2        3     Anjali            4           Satisfied
3        4      Rahul            5           Satisfied
4        5      Rohan            2        Dissatisfied
5        6     Anjali            4           Satisfied
6        7      Rahul            1        Dissatisfied
7        8      Rohan            5           Satisfied
8        9     Anjali            3        Dissatisfied
9       10      Rahul            4           Satisfied

In [44]:
#Task 12: Write an SQL query to find the Total Number of Calls for each Satisfaction_Status. Your output should show two columns: Satisfaction_Status (using the same CASE WHEN logic from Task 11) and Total_Calls

In [45]:
query12 = """
SELECT CASE 
            WHEN CSAT_Rating >= 4 THEN 'Satisfied' 
            ELSE 'Dissatisfied' 
       END AS 'Satisfaction_Status',
       COUNT(Call_ID) AS 'Total_Calls'
FROM call_logs
GROUP BY CASE 
              WHEN CSAT_Rating >= 4 THEN 'Satisfied' 
              ELSE 'Dissatisfied' 
         END
"""

In [46]:
result12 = pd.read_sql(query12,cust_conn)
result12

  Satisfaction_Status  Total_Calls
0        Dissatisfied            4
1           Satisfied            6

In [47]:
#Task 13: Write a Python script in your Jupyter Notebook to read all records from the call_logs table and export them into a CSV file named call_center_clean_data.csv. Ensure that the DataFrame index is not included in the file.

In [48]:
final_df = pd.read_sql("SELECT * FROM call_logs", cust_conn)

In [49]:
final_df.to_csv('call_center_clean_data.csv', index = False)

In [50]:
print ("Data exported successfully!")

Data exported successfully!

# 📊 Project Conclusion: Call Center Performance Analysis

This end-to-end data analytics project successfully integrates **SQL, Python (Pandas), Advanced Excel, and Power BI** to analyze and visualize raw call center logs. By transforming messy data into an interactive business dashboard, we uncovered key operational insights.

---

### 🔍 1. Business Management & Agent Performance
* **Anjali:** Handled the highest volume with **4 successful calls**, demonstrating strong efficiency and workload management.
* **Rahul & Rohan:** Balanced the remaining workload, handling **3 calls each**.
* **Total Volume:** A total of **10 customer interactions** were processed and analyzed during this evaluation period.

---

### 📉 2. Customer Satisfaction (CSAT) Metrics
* **Satisfied Customers:** **60% of customers** (6 out of 10) reported a positive experience, giving a CSAT rating of 4 or 5.
* **Dissatisfied Customers:** **40% of customers** (4 out of 10) expressed dissatisfaction, giving a CSAT rating below 4. This highlights a critical area for service quality improvement.

---

### 🛠️ 3. Technical Milestones & Core Learnings
1. **Data Manipulation (SQL):** Applied advanced techniques like `CASE WHEN`, `GROUP BY`, and aggregate functions (`COUNT`) to categorize and segment raw data directly from the database.
2. **Data Export (Python Pandas):** Leveraged `to_csv(index=False)` to export clean data structures without cluttering the final dataset with unnecessary row index columns.
3. **Data Summarization (Advanced Excel):** Utilized Pivot Tables and column auto-fitting to restructure data into corporate-ready summary tables.
4. **Interactive Dashboarding (Power BI):** Developed a dynamic dashboard using a Donut Chart and an interactive Slicer tool, allowing stakeholders to filter performance metrics by specific call topics instantly.

---

**💡 Final Business Recommendation:** With a 40% dissatisfaction rate, the management should focus on targeted agent training for unresolved 'Pending' issues, specifically focusing on complex customer complaints like 'Billing Issues' and 'Technical Support'.

Tools Used: SQL (Data Extraction), Python Pandas (Data Handling), Advanced Excel (Pivot & Basic Charting), Power BI (Interactive Slicers & Donut Dashboard).